name: StellarExpert Verify

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  attestations: write

jobs:
  release-rebalancer-admin:
    uses: stellar-expert/soroban-build-workflow/.github/workflows/release.yml@main
    with:
      release_name: v0.1.0-se
      package: 'rebalancer-admin'
      home_domain: 'lumenbro.com'
    secrets:
      release_token: ${{ secrets.GITHUB_TOKEN }}
